name: NetExec Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: NetExec Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: NetExec tests on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build binaries with Shiv
      run: |
        pip install shiv
        python build_collector.py
    - name: Upload nxc binary
      uses: actions/upload-artifact@master
      with:
        name: nxc-${{ matrix.os }}-${{ matrix.python-version }}
        path: bin/nxc
    - name: Upload nxcdb binary
      uses: actions/upload-artifact@master
      with:
        name: nxcdb-${{ matrix.os }}-${{ matrix.python-version }}
        path: bin/nxcdb
